spring:
  application:
    name: department-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

clients:
  services:
    employee-service:
      url: http://localhost:8082
    bank-account-service:
      url: http://localhost:8083