spring:
  application:
    name: payroll-service
  kafka:
    template:
      observation-enabled: true
    bootstrap-servers: localhost:19092
    producer:
      topic: payroll-topic
    consumer:
      topic: payroll-topic
      group-id: payroll-group-id
      retry:
        max-attempts: 3
    listener:
      observation-enabled: true

server:
  port: 8084

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health

clients:
  services:
    bank-account-service:
      url: http://localhost:8083