spring:
  application:
    name: employee-service

server:
  port: 8082

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health

clients:
  services:
    bank-account-service:
      url: http://localhost:8083